[[redirects]]
from = "/baapk/global"
to = "https://d.apkpure.net/b/XAPK/com.nexon.bluearchive?version=latest"
status = 200

[[redirects]]
from = "/baapk/jp"
to = "https://d.apkpure.net/b/XAPK/com.YostarJP.BlueArchive?version=latest"
status = 200

[[redirects]]
from = "/api/baapk.json"
to = "/baapk.json"
status = 200